Added UserRowMapper. Added getListOfUsers
RohtlaS/intranet pull request #6
Opened 2020-11-24 14:09 UTC by siiritann

2020-11-24 14:38 UTC, ottkaskjr approved these changes

2020-11-25 07:22 UTC, RohtlaS commented on src/main/java/com/intranet/project/controller/UserController.java
> +    @PostMapping("/create/user")
@RequestMapping("posting") ---- klassi ette
public class PostingController {

@PostMapping("/create") ---- meetodi ette
    public void createPosting(@RequestBody

2020-11-25 07:27 UTC, RohtlaS commented on src/main/java/com/intranet/project/repository/UserRowMapper.java
> +public class UserRowMapper implements RowMapper {
implements RowMapper järel peaks olema <UserEntity>

2020-11-25 07:27 UTC, RohtlaS commented on src/main/java/com/intranet/project/repository/UserRowMapper.java
> +public class UserRowMapper implements RowMapper {
<UserEntity>

2020-11-25 07:28 UTC, siiritann commented on src/main/java/com/intranet/project/controller/UserController.java
> +    @PostMapping("/create/user")
done

2020-11-25 07:32 UTC, RohtlaS requested changes
Kommentaarid sees

2020-11-25 07:36 UTC, siiritann commented on src/main/java/com/intranet/project/repository/UserRowMapper.java
> +public class UserRowMapper implements RowMapper {
done

2020-11-25 07:39 UTC, merged